### ISSUE TITLE
react-native-call-detection is not working with react-native 0.60.5

### ISSUE THREAD

**Issue by AsheeshPandey1995** [priteshrnandgaonkar/react-native-call-detection#44]
/react-native-60/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:90: error: constructor CallDetectionManager in class CallDetectionManager cannot be applied to given types;
      new CallDetectionManager(),
      ^
  required: Application
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details

**Comment by kailashvele** [comment]
Try adding following in your MainApplication.java

`@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new CallDetectionManager(MainApplication.this),`

**Comment by anurbecirovic** [comment]
Still the same problem

**Comment by DragonRaider5** [comment]
Please have a look at #42 . Comment there in case the issue persists.
