### ISSUE TITLE
Facing the issue while running with Android rror: constructor CallDetectionManager in class CallDetectionManager cannot be applied to given types; new CallDetectionManager()^

### ISSUE THREAD

**Issue by SnehalAgrawal** [priteshrnandgaonkar/react-native-call-detection#42]
Hey Hi,
I am facing issue while running the app on Android. Below are error logs. Is there any one who have the idea how to deal with it?

error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-call-detection (to unlink run: "react-native unlink react-native-call-detection")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1638 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
23 actionable tasks: 3 executed, 20 up-to-date
/Users/kepi/Desktop/RNWorkSapce/Sandesh/RNCallDetection/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:51: error: constructor CallDetectionManager in class CallDetectionManager cannot be applied to given types;
      new CallDetectionManager()
      ^
  required: Application
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/kepi/Desktop/RNWorkSapce/Sandesh/RNCallDetection/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:51: error: constructor CallDetectionManager in class CallDetectionManager cannot be applied to given types;
      new CallDetectionManager()
      ^
  required: Application
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/Users/kepi/Desktop/RNWorkSapce/Sandesh/RNCallDetection/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Users/kepi/Desktop/RNWorkSapce/Sandesh/RNCallDetection/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/kepi/Desktop/RNWorkSapce/Sandesh/RNCallDetection/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by usman-ghani127** [comment]
After adding and linking the package, disable auto linking of this package by adding
`
dependencies: {
    'react-native-call-detection': {
      platforms: {
        android: null, 
      },
    },
  },
`
to your react-native.config.js

**Comment by NareshNama** [comment]
i am also facing same issue any solution.

**Comment by anurbecirovic** [comment]
@usman-ghani127 Solution works, but the library doesn't work at all. Not sure why it's not recognizing any activity when calling or receiving calls.

**Comment by usman-ghani127** [comment]
> @usman-ghani127 Solution works, but the library doesn't work at all. Not sure why it's not recognizing any activity when calling or receiving calls.

You, probably, forgot to manually link the library. 
`react-native link  'react-native-call-detection'`

**Comment by roysG** [comment]
where should i find the file "react-native.config.js" ? 
I am using rn 0.61.5

**Comment by anurbecirovic** [comment]
@roysG create it manually in root folder of the project. 
![Screenshot 2019-12-09 at 08 46 56](https://user-images.githubusercontent.com/24942592/70416957-7cba7b00-1a60-11ea-98a1-7a70b7357596.png)

And just add this code 

`module.exports = {
  dependencies: {
    'react-native-call-detection': {
      platforms: {
        android: null,
      },
    },
  },
};`

Hope this will fix your problem

**Comment by keithhackbarth** [comment]
To anyone else that ran into this, my issue was that my MainApplication java had `new CallDetectionManager(MainApplication.this),` instead of `new CallDetectionManager()`. For some reason, unlink to link didn't solve. 

My steps were as follows:

- Upgrade library to latest version
- react-native unlink 'react-native-call-detection'
- Remove all orphaned references to CallDetectionManager from MainApplication.java
- react-native link 'react-native-call-detection'

**Comment by DragonRaider5** [comment]
Please comment in case @keithhackbarth 's solution did not work for you.
